site_name: ANotes
site_url: https://anotes.rtfd.io/
site_description: ANotes - useful notes
site_author: Anotes

repo_url: "" #https://github.com/ReadTheDcs/MkMod
edit_uri: ""

theme:
    name: material
    custom_dir: 'material/'
    logo: 'img/logo.png'
    feature: ''
    highlightjs: false
    hljs_languages:
        - yaml
        - django


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2020

#google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
