site_name: Tempmailin - temp email
site_url: https://tempmailin.com/
site_description: Tempmailin is website providing service for temp mail or also called 10 minute mail or disposable email.
site_author: Tempmailin.com

repo_url: "" #https://github.com/ReadTheDcs/MkMod
edit_uri: ""

theme:
    name: material
    custom_dir: 'material/'
    highlightjs: true
    hljs_languages:
        - yaml
        - django


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2019 <a href="https://tempmailin.com/">Tempmailin</a>, Project <a href="https://readthedocs.org/projects/atempmailin/" target="_blank">Home</a>.

#google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
